language: perl
perl:
  - "5.10.1"
  - "5.20.3"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
before_install:
  - "perlbrew use $TRAVIS_PERL_VERSION || (perlbrew install --notest $TRAVIS_PERL_VERSION && perlbrew switch $TRAVIS_PERL_VERSION)"
  - printenv
  - "perl --version"
  - "cpanm --version"
install:
  - "cpanm --notest Minilla"
script:
  - "minil test"
